
.PHONY: clean

exercicestp2: exercicestp2.hs
		ghc -Wall exercicestp2.hs -o exercicestp2

pascal: pascal.hs
		ghc -Wall pascal.hs -o pascal


dragon: dragon.hs
		ghc -Wall dragon.hs -o dragon 

clean:
	rm -vf *.o
	rm -vf *.hi
	rm -vf dragon
	rm -vf pascal
	rm -vf exercicestp2
